version: '3.8'

services:
  app:
    image: your-username/your-app:stag-${TAG:-latest}
    container_name: app-stag
    env_file:
      - .env.stag
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db-stag
    env_file:
      - .env.stag
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge